/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelhistory;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author peter john
 */
public class EditData extends javax.swing.JFrame {
    public static final MainMenu menu = new MainMenu();
    /**
     * Creates new form EditData
     */
    public EditData() {
        initComponents();
        MainMenu.data.clear();
        MainMenu.populateData();
        personComboBox.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18));
        personComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(getData()));
        
        nameInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getName());
        addressInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getAddress());
        locationInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getLocation());
        contactNumberInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getContactNumber());
        timeInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getTime());
        dateInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getDate());
        temperatureInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getTemperature());
        
    }
    public static String[] getData() {
        String[] data = new String[MainMenu.data.size()];
        
        for(int i = 0; i < MainMenu.data.size(); i++) {
            data[i] = MainMenu.data.get(i).getName();
        }
        return data;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        personComboBox = new javax.swing.JComboBox<>();
        inputPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        temparatureLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextField();
        locationInput = new javax.swing.JTextField();
        contactNumberInput = new javax.swing.JTextField();
        timeInput = new javax.swing.JTextField();
        dateInput = new javax.swing.JTextField();
        temperatureInput = new javax.swing.JTextField();
        editPerson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Edit Data");

        personComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        personComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personComboBoxActionPerformed(evt);
            }
        });

        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Travel History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        nameLabel.setText("Name");

        addressLabel.setText("Address");

        locationLabel.setText("Location");

        contactNumberLabel.setText("Contact number");

        timeLabel.setText("Time");

        dateLabel.setText("Date");

        temparatureLabel.setText("Temperature");

        editPerson.setText("Save");
        editPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(contactNumberLabel)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateLabel)
                            .addComponent(timeLabel)))
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(locationLabel)
                    .addComponent(temparatureLabel))
                .addGap(103, 103, 103)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactNumberInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressInput)
                    .addComponent(locationInput))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editPerson)
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberLabel)
                    .addComponent(contactNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temparatureLabel)
                    .addComponent(temperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(editPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(personComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(header)
                        .addGap(275, 275, 275))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addGap(18, 18, 18)
                .addComponent(personComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPersonActionPerformed
        // TODO add your handling code here:
        if(nameInput.getText().isEmpty() 
                || addressInput.getText().isEmpty()
                || locationInput.getText().isEmpty()
                || contactNumberInput.getText().isEmpty()
                || timeInput.getText().isEmpty()
                || dateInput.getText().isEmpty()
                || temperatureInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT THE FIELDS PROPERLY");
        } else {
            MainMenu.data.get(personComboBox.getSelectedIndex()).setName(nameInput.getText().trim());
            MainMenu.data.get(personComboBox.getSelectedIndex()).setAddress(addressInput.getText().trim());
            MainMenu.data.get(personComboBox.getSelectedIndex()).setLocation(locationInput.getText().trim());
            MainMenu.data.get(personComboBox.getSelectedIndex()).setContactNumber(contactNumberInput.getText().trim());
            MainMenu.data.get(personComboBox.getSelectedIndex()).setTime(timeInput.getText().trim());
            MainMenu.data.get(personComboBox.getSelectedIndex()).setDate(dateInput.getText().trim());
            MainMenu.data.get(personComboBox.getSelectedIndex()).setTemperature(temperatureInput.getText().trim());
            MainMenu.saveData();
            JOptionPane.showMessageDialog(null, "EDITED SUCCESSFULLY");
            menu.refreshTable();
            this.dispose();
        }
    }//GEN-LAST:event_editPersonActionPerformed

    private void personComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personComboBoxActionPerformed
        // TODO add your handling code here:
        nameInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getName());
        addressInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getAddress());
        locationInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getLocation());
        contactNumberInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getContactNumber());
        timeInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getTime());
        dateInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getDate());
        temperatureInput.setText(MainMenu.data.get(personComboBox.getSelectedIndex()).getTemperature());
        
    }//GEN-LAST:event_personComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField contactNumberInput;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JTextField dateInput;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton editPerson;
    private javax.swing.JLabel header;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField locationInput;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> personComboBox;
    private javax.swing.JLabel temparatureLabel;
    private javax.swing.JTextField temperatureInput;
    private javax.swing.JTextField timeInput;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
